all : dwed.exe dwed16.exe dwedovl.exe dwedovlp.exe

dwed.exe: dwed.pas dwedlnch.pas sysext.pas
        tpc -M -$D- -$G- -$R- -$S- -$I- -$R- -$E- dwed.pas

dwed16.exe: dwed16.pas dwedlnch.pas sysext.pas
        tpc -M -$D- -$G- -$R- -$S- -$I- -$R- -$E- dwed16.pas

dwedovl.exe: dwedovl.pas dwedtype.pas dwedhndl.pas dwedutil.pas strs.pas strsd.pas lfn.pas dwedhl.pas dwedscru.pas dwedhelp.obj dwedhelp.pas dwedhelp.obj scr.pas scrui.pas help.pas strutil.pas kbd.pas dwedmain.pas dwedaddo.pas dwedlnch.pas sysext.pas dwedpar.pas mouse.pas event.pas
        tpc -M -$D- $L- -$G- -$R- -$S- -$I- -$E- -$Q- $B- dwedovl.pas

dwedovlp.exe: dwedovl16.pas dwedtype.pas dwedhndl.pas dwedutil.pas strs.pas strsd.pas lfn.pas dwedhl.pas dwedscru.pas dwedhelp.obj dwedhelp.pas dwedhelp.obj scr.pas scrui.pas help.pas strutil.pas kbd.pas dwedmain.pas dwedaddo.pas dwedlnch.pas sysext.pas dwedpar.pas mouse.pas event.pas
        bpc -CP -M -$D- $L- -$G+ -$R- -$S- -$I- -$E- -$Q- $B- dwedovlp.pas

upx: dwed.exe
        upx -9 --8086 dwed.exe

dwed.hlp: dwed.txt hlpc.exe
        hlpc dwed.txt dwed.hlp

hlpc.exe: hlpc.pas help.pas
        tpc -M hlpc.pas

dwedhelp.obj: dwed.hlp
        bin2obj dwed.hlp dwedhelp.obj HELPBIN

clean:
        del *.ppu
        del *.tpu
        del *.tpp
        del *.a
        del *.so
        del *.bak
