all : dwed.exe

dwed.exe: dwed.pas dwedtype.pas dwedhndl.pas dwedutil.pas strs.pas strsd.pas lfn.pas dwedhl.pas dwedscru.pas dwedhelp.obj dwedhelp.pas dwedhelp.obj
	tpc -M -U..\LIBS dwed.pas

upx: dwed.exe
	upx -9 --8086 dwed.exe

dwed.hlp: dwed.txt hlpc.exe
	hlpc dwed.txt dwed.hlp

hlpc.exe: hlpc.pas
	tpc -M -U..\LIBS hlpc.pas

dwedhelp.obj: dwed.hlp
	bin2obj dwed.hlp dwedhelp.obj HELPBIN

test:
	tpc -M -U..\LIBS test.pas
clean:
	del *.tpu
